name: topos
version: 0.1.0.0
license: BSD3

extra-source-files:
- readme

dependencies:
- base
- bytestring
- containers
- fused-effects
- hashable
- megaparsec
- mtl
- optparse-applicative
- unbound
- unordered-containers
- utf8-string

library:
  source-dirs: src
  ghc-options: -Wall

executables:
  topos:
    main: Main.hs
    source-dirs: main
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - topos
