name: topos
version: 0.1.0.0
license: BSD3

extra-source-files:
- README.md

default-extensions:
- BangPatterns
- BinaryLiterals
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveAnyClass
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DerivingStrategies
- DerivingVia
- DeriveTraversable
- DoAndIfThenElse
- EmptyDataDecls
- ExistentialQuantification
- ExplicitNamespaces
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MagicHash
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
#- NoImplicitPrelude
- OverloadedStrings
- PartialTypeSignatures
- PatternGuards
- PatternSynonyms
- PolyKinds
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeFamilies
- TypeSynonymInstances
- UnboxedTuples
- ViewPatterns

dependencies:
- base
- bytestring
- containers
- hashable
- megaparsec
- mtl
- optparse-applicative
- primitive
- template-haskell
- text
- unordered-containers
- utf8-string

library:
  source-dirs: src
  ghc-options: -Wall

executables:
  topos:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -fllvm
    dependencies:
    - topos
