resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/16/31.yaml

packages:
- .

extra-deps:
  - git: https://github.com/NorfairKing/sydtest.git
    commit: 2c563d5a819c70aad9f4d4f044cd72880921039b
    subdirs:
      - sydtest
      - sydtest-discover
  - envparse-0.4.1@sha256:989902e6368532548f61de1fa245ad2b39176cddd8743b20071af519a709ce30,2842