name: Haskell CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v1
      with:
        ghc-version: '8.10.5'
        cabal-version: '3.4'

    - name: Set up Hlint
      uses: rwe/actions-hlint-setup@v1
      with:
        version: '3.3.1'

    - name: Run Hlint
      uses: rwe/actions-hlint-run@v2
      with:
        path: '["src/", "app/"]'
        fail-on: warning

    - run: cabal v2-update
    
    - run: cabal v2-freeze

    - name: Cache
      uses: actions/cache@v1
      env:
        cache-name: cache-build
      with:
        path: |
          dist-newstyle
          ~/.cabal/store
        key: ${{ runner.os }}-{{ hashFiles('cabal.project.freeze') }}
        restore-keys: |
          ${{ runner.os }}-

    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks

    - name: Build
      run: cabal build --enable-tests --enable-benchmarks all
    - name: Run tests
      run: cabal test all
